version: '3'

services:
  web:
    build: ./internal
    ports:
      - "8080:8080"
    environment:
      ENV: production
    depends_on:
      db:
        condition: service_healthy # 完全啟動才執行
      redis:
        condition: service_healthy
    restart: always
      
  db:
    build: ./mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=gin
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=user
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-uuser"]
      interval: 5s
      retries: 5
    restart: always
    
  redis: 
    build: ./redis
    ports:
      - 6380:6379
    environment:
      - BIND=redis
      - PASSWORD= 
      - DB=0
    volumes:
      - ./redis/:/data/
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
    restart: always