name: cd

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Deploy to EC2
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@ec2-18-166-61-81.ap-east-1.compute.amazonaws.com 'bash -s' << EOF
            cd ./dcard-golang-project
            docker-compose down
            git pull
            docker-compose up -d

            sleep 10

            DOCKER_COMPOSE_STATUS=$?

            if [ $DOCKER_COMPOSE_STATUS -eq 0 ]; then
                echo "Docker Compose started successfully."
            else
                echo "Docker Compose failed to start."
            fi
            exit $DOCKER_COMPOSE_STATUS
          EOF
