name: cd

on:
  pull_request:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Deploy to EC2
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@ec2-13-238-213-46.ap-southeast-2.compute.amazonaws.com 'bash -s' << EOF
            git clone git@github.com:huanciou/dcard-golang-project.git
            cd ./dcard-golang-project
            docker-compose up -d
            sleep 10
            docker-compose exec web ./run_test.sh
          EOF
