name: ci

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Install Docker
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker.io

      - name: Start Docker Compose
        run: |
          docker-compose up -d
        continue-on-error: true
        timeout-minutes: 5

      - name: Wait for services to become healthy
        run: |
          retries=0
          until docker-compose ps | grep -q "Up.*\(db\|redis\).*healthy"; do
            retries=$((retries+1))
            if [ $retries -gt 6 ]; then
              echo "Services did not become healthy within timeout period."
              exit 1
            fi
            sleep 10
          done

      - name: Run tests
        run: docker-compose exec -T web ./run_test.sh

      - name: Stop Docker Compose
        run: docker-compose down
