name: ci

on:
  push:
    branches: ['main', 'Dev']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start Docker Compose
        run: |
          docker-compose up -d
        continue-on-error: true
        timeout-minutes: 5

      - name: Run tests
        run: docker-compose exec -T web ./run_test.sh

      - name: Stop Docker Compose
        run: docker-compose down
