name: ci

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Install Docker
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker.io

      - name: Start Docker Compose
        run: |
          docker-compose up -d
          sleep 10

      - name: Run tests
        run: docker-compose exec web ./run_test.sh

      - name: Stop Docker Compose
        run: docker-compose down
